stages:
  get_data:
    cmd: python src/get_data.py
    deps:
    - src/get_data.py
    outs:
    - data/customer_churn.csv
  train_model:
    cmd: python src/train_model.py
    deps:
    - data/customer_churn.csv
    - src/train_model.py
    outs:
    - models/model.pkl
