stages:
  get_data:
    cmd: python src/get_data.py
    deps:
    - src/get_data.py
    outs:
    - data/customer_churn.csv
  train_model:
    cmd: python src/train_model.py
    deps:
    - data/customer_churn.csv
    - src/train_model.py
    params:
    - split.random_state
    - split.test_size
    - train.C
    - train.max_iter
    outs:
    - models/model.pkl
    - mlruns/:
        cache: false  # Prevent DVC from caching mlruns/