stages:
  get_data:
    cmd: python src/get_data.py
    deps:
      - src/get_data.py
    outs:
      - data/customer_churn.csv

  train_model:
    cmd: python src/train_model.py
    deps:
      - src/train_model.py
      - data/customer_churn.csv
    params:
      - split.test_size
      - split.random_state
      - train.C
      - train.max_iter
    outs:
      - models/model.pkl
