name: Run DVC Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dvc-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure full history for DVC

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install dvc[s3] mlflow scikit-learn pandas pyyaml joblib
        pip show mlflow  # Print MLflow version for debugging

    - name: Debug directory and files
      run: |
        pwd
        ls -la
        ls -la data/ || echo "data/ directory not found"
        ls -la models/ || echo "models/ directory not found"
        ls -la mlruns/ || echo "mlruns/ directory not found"

    - name: Reproduce pipeline with DVC
      run: |
        dvc repro

    - name: Display pipeline status
      run: |
        dvc status

    - name: Archive MLflow artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mlflow-artifacts
        path: |
          mlruns/
          models/
        retention-days: 7