name: CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run-mlops:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: file:./mlruns
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc dvc-gdrive
    - name: Ensure mlruns directory
      run: mkdir -p mlruns && chmod -R 777 mlruns
    - name: Run DVC pipeline
      run: dvc repro
    - name: Debug mlruns contents
      run: ls -la mlruns/ || echo "mlruns/ is empty or missing"
    - name: Upload MLflow artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mlruns
        path: mlruns/
        retention-days: 7