name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-mlops:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: file:./mlruns

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc dvc-gdrive

    - name: Run DVC pipeline
      run: dvc repro

