name: Run DVC Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dvc-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install dvc[s3]  # add [gs] if you ever use Google Cloud

    - name: Reproduce pipeline with DVC
      run: |
        dvc repro

    - name: Display pipeline status
      run: |
        dvc status

