name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-mlops:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: file:./mlruns
      GITHUB_ACTIONS: true
      GITHUB_RUN_ID: ${{ github.run_id }}
      GITHUB_WORKFLOW: ${{ github.workflow }}
      GITHUB_JOB: ${{ github.job }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc dvc-gdrive

    - name: Create mlruns directory
      run: mkdir -p mlruns && chmod -R 777 mlruns

    - name: Run DVC pipeline
      run: dvc repro

    - name: Check MLflow run output
      run: |
        echo "Experiment folders:"
        ls -la mlruns/
        echo "Any runs logged:"
        find mlruns/ -type d -name '[0-9]*' || echo "No run folders found"

    - name: Upload MLflow artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mlruns
        path: mlruns/
        retention-days: 7
